#!/bin/sh
# A single script to generate an entry in for userlist.txt
# Usage:
#
# ./generate-userlist >> userlist.txt
# ./generate-userlist usernaem >> userlist.txt
#

if [[ $# -eq 1 ]]; then
  USERNAME="$1"
else
  read -p "Enter username: " USERNAME
fi

read -s -p "Enter password: " PASSWORD
echo >&2

# Using openssl md5 to avoid differences between OSX and Linux (`md5` vs `md5sum`)
encrypted_password="md5$(printf "$PASSWORD$USERNAME" | openssl md5)"

echo "\"$USERNAME\" \"$encrypted_password\""
